[theme]
base                = "dark"
primaryColor        = "#f97316"
backgroundColor     = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor           = "#E2E8F0"
font                = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
